{{- /* Backend Deployment */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-web-app.fullname" . }}-backend
  labels:
{{ include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ default .Values.replicaCount .Values.backend.replicaCount }}
  selector:
    matchLabels:
{{ include "my-web-app.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "my-web-app.backendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          {{- with .Values.backend.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}

---
{{- /* Frontend Deployment */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-web-app.fullname" . }}-frontend
  labels:
{{ include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ default .Values.replicaCount .Values.frontend.replicaCount }}
  selector:
    matchLabels:
{{ include "my-web-app.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "my-web-app.frontendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-static
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "my-web-app.fullname" . }}-frontend-config
        - name: nginx-static
          configMap:
            name: {{ include "my-web-app.fullname" . }}-frontend-config
