{{- /* Backend Service */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.fullname" . }}-backend-svc
  labels:
{{ include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
{{ include "my-web-app.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}

---
{{- /* Frontend Service */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.fullname" . }}-frontend-svc
  labels:
{{ include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
{{ include "my-web-app.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
